networks:
  system_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.77.0.0/16

services:
  app:
    build:
      context: .
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - "48002:8000"
    env_file:
      - .env
    environment:
      - REDIS_HOST=cache
    networks:
      system_network:
    container_name: app
    depends_on:
      - cache
  
  cache:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"


